README.md

In scratch orgs `ExternalSharing` is enabled by default,
so it makes sense to show how to disable it.
[ci skip]

docs: update example to disable ExternalSharing

---

.travis.yml

[Travis CI fails to create a scratch org](https://salesforce.stackexchange.com/questions/210794/travis-ci-fails-to-create-a-scratch-org)

chore(CI): temporary use MacOS in Travis

---

package.json
yarn.lock

This makes it possible to declare `sfdx-browserforce-plugin`
as a dependency in a Node.js project
to prevent installing it globally with sfdx.
```console
npm install --save-dev sfdx-browserforce-plugin
```
You can then use the binary using `npx`
```console
npx sfdx-browserforce-plugin browserforce:shape:apply ...
```
or inside _npm scripts_ (`package.json`)
```json
{
"scripts": {
"dev:org": "sfdx force:org create ...",
"dev:browserforce": "sfdx-browserforce-plugin browserforce:shape:apply ...",
"dev": "npm run dev:org && npm run dev:browserforce"
}
}
```

feat: sfdx-browserforce-plugin binary

---

src/plugins/admins-can-log-in-as-any/index.ts
src/plugins/customer-portal/index.ts
src/plugins/salesforce-to-salesforce/index.ts

The SalesforceToSalesforce tests failed from time to time in CI.
Use `page.$eval` as seen here:
https://github.com/adonisjs/vow-browser/blob/59c5a20a2f04db4dda315efe916dbf9385bd26d9/src/Browser/ActionsChain.js#L134

fix: try to make setting checkboxes less flaky

---

package.json
src/commands/browserforce/shape/apply.ts
src/plugins/admins-can-log-in-as-any/index.e2e-spec.ts
src/plugins/customer-portal/index.e2e-spec.ts
src/plugins/external-sharing/index.e2e-spec.ts
src/plugins/salesforce-to-salesforce/index.e2e-spec.ts
yarn.lock

This prevents the process from hanging on exit.
The exit code 1 is being returned on error.
By switching from bluebird promise to async/await,
the dependency bluebird is now removed.

fix: exiting the process

---

src/browserforce.ts
src/browserforceCommand.ts
src/plugins/customer-portal/availableCustomObjects/index.ts
src/plugins/customer-portal/enabled/index.ts
src/plugins/customer-portal/index.e2e-spec.ts
src/plugins/customer-portal/portals/index.ts
src/plugins/home-page-layouts/index.e2e-spec.ts
src/plugins/home-page-layouts/index.ts
src/plugins/index.ts
src/plugins/salesforce-to-salesforce/index.e2e-spec.ts
src/plugins/salesforce-to-salesforce/index.ts
src/plugins/security/certificate-and-key-management/index.ts
src/plugins/security/identity-provider/index.ts
src/plugins/security/index.e2e-spec.ts
src/plugins/security/login-access-policies/index.e2e-spec.ts
src/plugins/security/login-access-policies/index.ts
src/plugins/security/sharing/index.e2e-spec.ts
src/plugins/security/sharing/index.ts
src/plugins/utils.ts
test/browserforce.e2e-spec.ts
test/utils.test.ts

Logging in using frontdoor sometimes stops at URLs like `https://test.salesforce.com/?ec=302&startURL=` indicating the login failed.
However the login was successful.
Opening another page with the instance URL in the same browser seems to
do the trick.
Encapsulate retry logic in browserforce.openPage
- resolve IP addresses of classic and LEX domains
- check response for errors
This should resolve many errors like
> ERROR running BrowserforceApply:
> waiting for selector "#penabled" failed: timeout 30000ms exceeded
and
> ERROR running BrowserforceApply:
> login failed [302]: {"instanceUrl": "https://velocity-speed-2098-dev-ed.cs50.my.salesforce.com/, "url": "https://test.salesforce.com"}"

fix: workaround for timeouts and redirect issues on frontdoor

---

src/browserforce.ts

The personal information page (`setup/personalInformationSetup.apexp`)
seems to be not available in all orgs.

fix: set login retURL to setup page

---

.vscode/launch.json
README.md
src/browserforce.ts
test/browserforce.e2e-spec.ts

This should reveal errors like
> An error has occurred in the following section: [Exception, DomainNotPropagated_desc].
> Salesforce.com has been notified of this error.

fix: throw page error on 500 if there is one

---

tslint.json

Error message:
> Invalid "extends" configuration value - could not require "@salesforce/dev-config/tslint".

chore: fix prettier

---

README.md

By making the JSON valid and moving the schema into the JSON object

docs: fix example configuration file in the README

---

src/plugins/density-settings/index.ts
src/plugins/lightning-experience-settings/index.ts

The element `lightning-formatted-text` was changed to `lightning-base-formatted-text`.
This change now supports both elements to be backwards compatible.

fix: change in DOM of LEX themes page

---

src/browserforce.ts

Sometimes the instanceUrl contains a trailing slash.
When building a URL for opening in the browser,
this can lead to two consecutive slashes.
This removes trailing slashes to prevent this.

fix: prevent ERR_TOO_MANY_REDIRECTS

---

src/plugins/picklists/pages.ts

The XPath expression to crawl active and inactive
picklist values was inaccurate.

fix: XPath for crawling picklist values

---

README.md
src/plugins/picklists/activate.json
src/plugins/picklists/deactivate.json
src/plugins/picklists/index.e2e-spec.ts
src/plugins/picklists/index.ts
src/plugins/picklists/pages.ts
src/plugins/picklists/schema.json

Example config for deactivating a picklist value:
```json
{
"$schema": "https://raw.githubusercontent.com/amtrack/sfdx-browserforce-plugin/master/src/plugins/schema.json",
"settings": {
"picklists": {
"picklistValues": [
{
"metadataType": "CustomField",
"metadataFullName": "Vehicle__c.Features__c",
"value": "AC",
"active": false
}
]
}
}
}
```

feat: (de)activate picklist values

---

src/browserforce.ts
src/plugins/picklists/field-dependencies/change.json
src/plugins/picklists/field-dependencies/index.ts
src/plugins/picklists/field-dependencies/pages.ts
src/plugins/picklists/field-dependencies/schema.json
src/plugins/picklists/field-dependencies/set.json
src/plugins/picklists/field-dependencies/unset.json
src/plugins/picklists/index.e2e-spec.ts
src/plugins/picklists/index.ts
src/plugins/picklists/schema.json

Manage (create/modify/delete) Field Dependencies on CustomFields.
If a Field Dependency already exists for the dependent field,
it will be deleted.
In general the Metadata and Tooling API can be used for this.
However these APIs throw the following error when trying to change
field dependencies for **installed** CustomFields:
> Cannot modify managed object: entity=CustomFieldDefinition,
component=00NXXXXXXXXXXXX, field=PicklistControllerEnumOrId,
state=installed, newValue='00NYYYYYYYYYYYY', oldValue='null'
**Examples**
Make sure the given field dependency exists:
```json
{
"$schema": "https://raw.githubusercontent.com/amtrack/sfdx-browserforce-plugin/master/src/plugins/schema.json",
"settings": {
"picklists": {
"fieldDependencies": [
{
"object": "Vehicle__c",
"dependentField": "Gears__c", …
```

feat: allow managing field dependencies (on installed CustomFields) 

---

README.md
config/project-scratch-def.json
src/plugins/high-velocity-sales-settings/disable.json
src/plugins/high-velocity-sales-settings/enable.json
src/plugins/high-velocity-sales-settings/index.e2e-spec.ts
src/plugins/high-velocity-sales-settings/index.ts
src/plugins/high-velocity-sales-settings/page.ts
src/plugins/high-velocity-sales-settings/schema.json
src/plugins/index.ts
src/plugins/schema.json

Due to a bug, High Velocity Sales needs to be set up and enabled
initially using the UI.
Once set up, it can be configured using HighVelocitySalesSettings Metadata
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_highvelocitysalessettings.htm
Fixes #375

feat: "Set Up and Enable High Velocity Sales"

---

src/plugins/picklists/index.e2e-spec.ts
src/plugins/picklists/index.ts
src/plugins/picklists/new.json
src/plugins/picklists/pages.ts
src/plugins/picklists/replace-and-delete.json
src/plugins/picklists/schema.json
src/plugins/picklists/sfdx-source/standardValueSets/AccountType.standardValueSet-meta.xml
src/plugins/picklists/sfdx-source/standardValueSets/ContractStatus.standardValueSet-meta.xml

Support for new picklist values in GlobalValueSets, CustomFields and StandardValueSets (including Status StandardValueSets).
Closes #432

feat: extend picklists plugin to allow "New" picklist values

---

src/plugins/defer-sharing-calculation/index.ts

After running the command I noticed that the sharing recalculation would not execute. I have added a wait step for the recalculation button ahead of clicking it.

fix: Allow sharing recalculation to execute

---

src/plugins/defer-sharing-calculation/index.ts

I was seeing an intermittent error on the recalculation, looking into the code it seems the wait was on the original page which will likely have already loaded the recalculate button.

fix: Sharing Recalculation Intermittent Error

---

src/plugins/high-velocity-sales-settings/index.e2e-spec.ts

In the Winter '23 Release (API v56.0) this license for the feature doesn't seem to be available in Scratch Orgs anymore.

test: disable test for HighVelocitySalesSettings

---

src/plugins/high-velocity-sales-settings/index.e2e-spec.ts
src/plugins/high-velocity-sales-settings/page.ts

High Velocity Sales changed names to Sales Engagement so enabling and disabling the feature no longer works.  May need to update all functionality to Sales Engagement at some point, but for now getting enable/disable back up and running.

Update hvs Url due to name change

---

src/plugins/index.ts
src/plugins/opportunity-splits/disable.json
src/plugins/opportunity-splits/enable.json
src/plugins/opportunity-splits/index.e2e-spec.ts
src/plugins/opportunity-splits/index.ts
src/plugins/opportunity-splits/pages/layout-selection.ts
src/plugins/opportunity-splits/pages/overview.ts
src/plugins/opportunity-splits/pages/setup.ts
src/plugins/opportunity-splits/schema.json
src/plugins/opportunity-splits/sfdx-source/settings/Opportunity.settings-meta.xml
src/plugins/schema.json

As prerequisite Opportunity Teams must be enabled.
This can be done e.g. by deploying 'Settings:Opportunity' containing
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpportunitySettings xmlns="http://soap.sforce.com/2006/04/metadata">
<enableOpportunityTeam>true</enableOpportunityTeam>
</OpportunitySettings>
```
Fixes #508

feat: Opportunity Splits

---

.github/workflows/default.yml
.github/workflows/preview.yml

Use bash process substitution which makes the input appear as a filename instead of /dev/stdin.

chore: refactor org login from environment variable

---

README.md
package.json
src/browserforce.ts
yarn.lock

BREAKING CHANGE:
Puppeteer now uses "Chrome for Testing" instead of Chromium. This should make the installation of puppeteer's browser more stable especially on Mac computers with Apple silicon (M1/M2/M3).
We now use the new headless mode of Chrome.
A new README section related to Puppeteer is now available: https://github.com/amtrack/sfdx-browserforce-plugin/blob/master/README.md#puppeteer

fix: upgrade puppeteer to v21 now using "Chrome for Testing"

---

src/plugins/defer-sharing-calculation/sfdx-source/permissionsets/Defer_Sharing.permissionset-meta.xml

Permission DeferSharingCalculations depends on permission(s): FreezeUsers, MonitorLoginHistory

test: fix v61.0 PermissionSet userPermission deps

---

src/plugins/customer-portal/available-custom-objects/index.ts

The CustomerPortal plugin now allows to make a CustomObject available for the CustomerPortal when the CustomObject already has been deleted and recreated before.
This is typically the case when running E2E tests repeatedly.

fix: improve handling of deleted CustomObjects in CustomerPortal plugin

---

CONTRIBUTING.md
src/plugins/security/authentication-configuration/disable.json
src/plugins/security/authentication-configuration/enable.json
src/plugins/security/authentication-configuration/index.e2e-spec.ts
src/plugins/security/authentication-configuration/index.ts
src/plugins/security/authentication-configuration/schema.json
src/plugins/security/authentication-configuration/sfdx-source/authproviders/TestAuthMethod.authprovider
src/plugins/security/index.ts
src/plugins/security/schema.json

Attempt at solving #673 
This currently works for classic, but not lightning. The page seems to load lightning based on prior session visits to setup, so the (limited) e2e tests do not pass when running the whole suite. It also can't disable the default Login Form if there are no other services, so the todo is needing to insert a dummy Auth/Saml provider to have available for adding more test coverage. 
To fix the lightning issue, I dabbled with `waitForSelectorInFrameOrPage` and it worked for retrieval, but (oddly) only when using the debug delay.. I think the iframe may flash a few times confusing the DOM. Even with the delay it didn't like locating the checkboxes to enable, but that may have been user error. 
@amtrack If you have any tips for working in the iframe or forcing it to load …

feat: enable auth services in Authentication Configuration (My Domain)
